project:
  type: website

website:
  title: "FindingNEMO"
  image: "images/shoal.png"
  favicon: "images/fishbone-icon.png"
  navbar:
    logo: "images/shoal.png"
    title: false
    collapse-below: lg
    search: true
    right:
      - text: "The Team"
        href: about.html
      - text: "Proposal"
        href: proposal/proposal.html
      - text: "Prototyping"
        menu:
          - text: "Introduction"
            href: prototyping/intro_proto.html
          - text: "Data Preparation"
            href: prototyping/data_prep.html
          - text: "Exploratory Data Analysis"
            href: prototyping/eda.html
          - text: "Clustering Analysis"
            href: prototyping/clustering.html
          - text: "Whole Project"
            href: prototyping/Project.html
      - text: "Shiny App"
        menu:
          - text: "User Guide"
            href: shinyapp/shinyapp1.html
          - text: "Shiny App"
            href: shinyapp/shinyapp2.html
      - text: "Project Overview"
        href: poster/poster.png
format:
  html:
    grid:
      margin-width: 150px
    toc: true
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css

editor: visual

